### ISSUE TITLE
have same errors while starting winlogs.py file 

### ISSUE THREAD

**Issue by isemennikov** [isemennikov/bash_for_cybersecurity#1]
hi everyone 

have some errors  while start winlogs.py file 

Windows PowerShell:
Windows.Globalization/Analytic:
WordChannel:
muxencode:
Traceback (most recent call last):
  File "C:\Users\sirius\bash_for_cybersecurity\CP_5_Reserch_Information\winlogs_2.py", line 54, in <module>
    main(args.log_dir)
  File "C:\Users\sirius\bash_for_cybersecurity\CP_5_Reserch_Information\winlogs_2.py", line 30, in main
    tar.add(evtx_file, arcname=os.path.basename(evtx_file))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tarfile.py", line 2164, in add
    tarinfo = self.gettarinfo(name, arcname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tarfile.py", line 2037, in gettarinfo
    statres = os.lstat(name)
              ^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] ▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒: 'C:/temp/logs\\LAPTOP-8J1PRQ2E_Microsoft-RMS-MSIPC-Debug.evtx'

**Comment by isemennikov** [comment]
muxencode:
Traceback (most recent call last):
  File "C:\Users\sirius\bash_for_cybersecurity\CP_5_Reserch_Information\winlogs_2.py", line 55, in <module>
    main(args.log_dir)
  File "C:\Users\sirius\bash_for_cybersecurity\CP_5_Reserch_Information\winlogs_2.py", line 31, in main
    tar.add(evtx_file, arcname=os.path.basename(evtx_file))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tarfile.py", line 2164, in add
    tarinfo = self.gettarinfo(name, arcname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tarfile.py", line 2037, in gettarinfo
    statres = os.lstat(name)
              ^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] ▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒: 'C:/temp/logs\\LAPTOP-8J1PRQ2E_Microsoft-RMS-MSIPC-Debug.evtx'

**Comment by isemennikov** [comment]
muxencode:
Traceback (most recent call last):
  File "C:\Users\sirius\bash_for_cybersecurity\CP_5_Reserch_Information\winlogs_2.py", line 55, in <module>
    main(args.log_dir)
  File "C:\Users\sirius\bash_for_cybersecurity\CP_5_Reserch_Information\winlogs_2.py", line 31, in main
    tar.add(evtx_file, arcname = evtx_file.name)
                                 ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'name'
